name: autopublish

on:
  schedule:
    - cron: '0 */2 * * *'   # запуск каждые 2 часа UTC
  workflow_dispatch:        # возможность запустить вручную

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # ── 1. Чекаут репозитория, используя PAT_TOKEN ──────────────────────────
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}
          fetch-depth: 0     # клонируем всю историю, чтобы git push точно работал

      # ── 2. Устанавливаем Python 3.11 ────────────────────────────────────────
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # ── 3. Устанавливаем зависимости ───────────────────────────────────────
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # ── 4. Собираем идеи ────────────────────────────────────────────────────
      - name: Run TrendScout (collect ideas)
        run: python scripts/trendscout.py

      # ── 5. Генерируем контент ───────────────────────────────────────────────
      - name: Run ContentForge (generate posts)
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: python scripts/contentforge.py

      # ── 6. Коммитим и пушим новые статьи, используя PAT в URL ───────────────
      - name: Commit & Push generated posts
        env:
          PAT: ${{ secrets.PAT_TOKEN }}
        run: |
          git config user.name 'auto-bot'
          git config user.email 'bot@example.com'

          # Ваша основная ветка (замените на master, если у вас master)
          BRANCH=main

          # Переключаемся на основную ветку и подтягиваем последние изменения
          git checkout $BRANCH
          git pull origin $BRANCH

          # Добавляем папку с новыми .md/.png
          git add website/content/posts

          # Если есть staged-изменения, коммитим
          git diff --cached --quiet || git commit -m "auto: new posts $(date -u +'%Y-%m-%dT%H:%M:%SZ')"

          # Пушим, указывая PAT прямо в URL. Лог GitHub Actions подставит вместо PAT «***».
          git push https://x-access-token:${PAT}@github.com/Pollo8/auto-publisher.git $BRANCH

      # ── 7. (Опционально) Уведомляем Cloudflare Worker ───────────────────────
      - name: Notify Cloudflare Worker
        run: |
          for file in website/content/posts/*.md; do
            title=$(grep '^title:' "$file" | head -1 | cut -d '"' -f2)
            slug=$(basename "$file" .md)
            url="https://Pollo8.github.io/auto-publisher/${slug}"
            curl -X POST https://<ВАШ_WORKER_URL> \
                 -H "Content-Type: application/json" \
                 -d "{\"title\":\"$title\",\"url\":\"$url\"}"
          done
